export const BRAND = {
  name: "Jandify Global",
  tagline: "Your Guide to Universities Worldwide",
  email: "hello@jandifyglobal.com",
  phone: "+234 800 000 0000",
  whatsapp: "https://wa.me/2348000000000",
  instagram: "https://instagram.com/jandifyglobal",
  instagramHandle: "@jandifyglobal",
  telegram: "https://t.me/jandifyglobal",
  youtube: "https://youtube.com/@jandifyglobal",
  twitter: "https://twitter.com/jandifyglobal",
  address: "Lagos, Nigeria",
  established: "2019",
  studentsHelped: "2,500+",
  universitiesCount: "10,000+",
  countriesCount: "60+",
  expertsCount: "15+",
};

export const NAV_ITEMS = [
  {
    label: "Countries",
    href: "/countries",
    mega: true,
    items: [
      { label: "United Kingdom", href: "/countries/united-kingdom", flag: "🇬🇧" },
      { label: "Germany", href: "/countries/germany", flag: "🇩🇪" },
      { label: "Canada", href: "/countries/canada", flag: "🇨🇦" },
      { label: "Australia", href: "/countries/australia", flag: "🇦🇺" },
      { label: "United States", href: "/countries/united-states", flag: "🇺🇸" },
      { label: "France", href: "/countries/france", flag: "🇫🇷" },
      { label: "Netherlands", href: "/countries/netherlands", flag: "🇳🇱" },
      { label: "Ireland", href: "/countries/ireland", flag: "🇮🇪" },
      { label: "Portugal", href: "/countries/portugal", flag: "🇵🇹" },
      { label: "Sweden", href: "/countries/sweden", flag: "🇸🇪" },
      { label: "Poland", href: "/countries/poland", flag: "🇵🇱" },
      { label: "UAE", href: "/countries/uae", flag: "🇦🇪" },
    ],
  },
  {
    label: "Universities",
    href: "/universities",
    mega: false,
    items: [
      { label: "Search Universities", href: "/universities" },
      { label: "Top 100 World Rankings", href: "/universities?sort=ranking" },
      { label: "Free Universities", href: "/universities?cost=free" },
      { label: "Online Programs", href: "/universities?mode=online" },
    ],
  },
  {
    label: "Programs",
    href: "/programs",
    mega: false,
    items: [
      { label: "Bachelor's Degree", href: "/programs?level=bachelor" },
      { label: "Master's Degree", href: "/programs?level=master" },
      { label: "MBA", href: "/programs?level=mba" },
      { label: "PhD / Doctorate", href: "/programs?level=phd" },
      { label: "Language Courses", href: "/programs?level=language" },
    ],
  },
  {
    label: "Admission",
    href: "/about#admission",
    mega: false,
    items: [
      { label: "How It Works", href: "/about#how-it-works" },
      { label: "Document Checklist", href: "/about#documents" },
      { label: "Scholarship Guide", href: "/articles/scholarship-guide" },
      { label: "Visa Guide", href: "/articles/visa-guide" },
    ],
  },
  {
    label: "Articles",
    href: "/articles",
    mega: false,
    items: [],
  },
];

export const COUNTRIES = [
  {
    slug: "united-kingdom",
    name: "United Kingdom",
    flag: "🇬🇧",
    region: "Europe",
    capital: "London",
    language: "English",
    currency: "GBP (£)",
    population: "67 million",
    heroImage: "/assets/countries/uk.jpg",
    summary: "World-class universities with globally recognized degrees and strong graduate employment outcomes.",
    tuitionRange: "£10,000 – £38,000/year",
    livingCost: "£12,000 – £18,000/year",
    intakeMonths: ["September", "January"],
    visaType: "Student Visa (Tier 4)",
    processingTime: "3–8 weeks",
    ieltsRequired: "6.0 – 7.0",
    topUniversities: ["University of Oxford", "University of Cambridge", "Imperial College London", "UCL", "University of Edinburgh"],
    pros: ["World-renowned degrees", "English-speaking", "Post-study work visa (2 years)", "Strong alumni networks", "Cultural diversity"],
    cons: ["High tuition and living costs", "Competitive admission", "Weather"],
    popularCourses: ["Business & Management", "Engineering", "Law", "Medicine", "Computer Science"],
    scholarships: ["Chevening Scholarship", "Commonwealth Scholarship", "Gates Cambridge", "University-specific bursaries"],
  },
  {
    slug: "germany",
    name: "Germany",
    flag: "🇩🇪",
    region: "Europe",
    capital: "Berlin",
    language: "German / English",
    currency: "EUR (€)",
    population: "84 million",
    heroImage: "/assets/countries/germany.jpg",
    summary: "Free tuition at public universities, strong engineering programs, and a thriving job market.",
    tuitionRange: "Free – €3,000/year (public)",
    livingCost: "€8,000 – €12,000/year",
    intakeMonths: ["October", "April"],
    visaType: "German Student Visa",
    processingTime: "4–8 weeks",
    ieltsRequired: "6.0 – 6.5 (English programs)",
    topUniversities: ["LMU Munich", "TU Munich", "Heidelberg University", "Humboldt University", "KIT"],
    pros: ["Free/low tuition at public universities", "Strong engineering & tech industry", "18-month post-study work visa", "Central location in Europe"],
    cons: ["German language often required", "Bureaucratic processes", "Competitive programs"],
    popularCourses: ["Engineering", "Computer Science", "Business", "Medicine", "Natural Sciences"],
    scholarships: ["DAAD Scholarship", "Deutschlandstipendium", "Heinrich Böll Foundation", "Konrad Adenauer Foundation"],
  },
  {
    slug: "canada",
    name: "Canada",
    flag: "🇨🇦",
    region: "North America",
    capital: "Ottawa",
    language: "English / French",
    currency: "CAD ($)",
    population: "38 million",
    heroImage: "/assets/countries/canada.jpg",
    summary: "Top-ranked universities, excellent quality of life, and clear pathways to permanent residency.",
    tuitionRange: "CAD $15,000 – $35,000/year",
    livingCost: "CAD $12,000 – $20,000/year",
    intakeMonths: ["September", "January"],
    visaType: "Canadian Study Permit",
    processingTime: "4–12 weeks",
    ieltsRequired: "6.0 – 7.0",
    topUniversities: ["University of Toronto", "McGill University", "UBC", "University of Waterloo", "McMaster"],
    pros: ["Clear PR pathway (Express Entry)", "Work while studying (20 hrs/week)", "3-year PGWP after graduation", "Safe, multicultural"],
    cons: ["High cost of living in major cities", "Cold winters", "Competitive visa process"],
    popularCourses: ["Business", "Engineering", "Computer Science", "Healthcare", "Hospitality"],
    scholarships: ["Vanier Canada Graduate", "Banting Postdoctoral", "University scholarships", "Provincial funding"],
  },
  {
    slug: "australia",
    name: "Australia",
    flag: "🇦🇺",
    region: "Oceania",
    capital: "Canberra",
    language: "English",
    currency: "AUD ($)",
    population: "26 million",
    heroImage: "/assets/countries/australia.jpg",
    summary: "World-class education, sunny lifestyle, and strong post-study work opportunities.",
    tuitionRange: "AUD $20,000 – $45,000/year",
    livingCost: "AUD $18,000 – $24,000/year",
    intakeMonths: ["February", "July"],
    visaType: "Student Visa (Subclass 500)",
    processingTime: "4–6 weeks",
    ieltsRequired: "6.0 – 7.0",
    topUniversities: ["University of Melbourne", "ANU", "University of Sydney", "UNSW", "Monash University"],
    pros: ["High quality of life", "Post-study work visa (2–4 years)", "No work restrictions during studies", "Diverse, welcoming culture"],
    cons: ["High living and tuition costs", "Distance from Africa/Europe", "Competitive job market"],
    popularCourses: ["Business", "Engineering", "Nursing", "IT", "Accounting"],
    scholarships: ["Australia Awards", "Destination Australia", "University grants", "Endeavour Scholarships"],
  },
  {
    slug: "united-states",
    name: "United States",
    flag: "🇺🇸",
    region: "North America",
    capital: "Washington D.C.",
    language: "English",
    currency: "USD ($)",
    population: "331 million",
    heroImage: "/assets/countries/usa.jpg",
    summary: "Home to the world's top-ranked universities and a vibrant international student community.",
    tuitionRange: "$10,000 – $60,000/year",
    livingCost: "$10,000 – $20,000/year",
    intakeMonths: ["August", "January"],
    visaType: "F-1 Student Visa",
    processingTime: "2–8 weeks",
    ieltsRequired: "6.5 – 7.5",
    topUniversities: ["MIT", "Harvard University", "Stanford University", "Caltech", "Columbia University"],
    pros: ["World's best universities", "Optional Practical Training (OPT)", "Innovation ecosystem", "Research funding"],
    cons: ["Very high tuition costs", "Complex visa process", "High cost of living in major cities"],
    popularCourses: ["Business", "Computer Science", "Engineering", "Law", "Medicine"],
    scholarships: ["Fulbright Program", "Hubert Humphrey", "University merit scholarships", "NSF Fellowships"],
  },
  {
    slug: "france",
    name: "France",
    flag: "🇫🇷",
    region: "Europe",
    capital: "Paris",
    language: "French / English",
    currency: "EUR (€)",
    population: "68 million",
    heroImage: "/assets/countries/france.jpg",
    summary: "Affordable public universities, prestigious grandes écoles, and a rich cultural experience.",
    tuitionRange: "€170 – €15,000/year",
    livingCost: "€9,000 – €15,000/year",
    intakeMonths: ["September"],
    visaType: "French Long-Stay Student Visa",
    processingTime: "3–6 weeks",
    ieltsRequired: "5.5 – 6.5 (English programs)",
    topUniversities: ["École Normale Supérieure", "École Polytechnique", "Sciences Po", "HEC Paris", "Sorbonne University"],
    pros: ["Very low public university fees", "Eiffel Excellence Scholarship", "Cultural richness", "EU work opportunities"],
    cons: ["French language usually required", "Complex bureaucracy", "Competitive grandes écoles"],
    popularCourses: ["Fashion & Design", "Business", "Engineering", "Political Science", "Arts"],
    scholarships: ["Eiffel Excellence Scholarship", "French Government Grants", "Campus France funding"],
  },
  {
    slug: "netherlands",
    name: "Netherlands",
    flag: "🇳🇱",
    region: "Europe",
    capital: "Amsterdam",
    language: "Dutch / English",
    currency: "EUR (€)",
    population: "17 million",
    heroImage: "/assets/countries/netherlands.jpg",
    summary: "Hundreds of English-taught programs and a globally connected, innovative academic environment.",
    tuitionRange: "€2,000 – €20,000/year",
    livingCost: "€10,000 – €15,000/year",
    intakeMonths: ["September", "February"],
    visaType: "Dutch Study Visa / MVV",
    processingTime: "3–5 weeks",
    ieltsRequired: "6.0 – 7.0",
    topUniversities: ["TU Delft", "University of Amsterdam", "Leiden University", "Wageningen University", "Erasmus University"],
    pros: ["Many English programs", "Bicycle-friendly cities", "1-year job search visa", "Innovative startup ecosystem"],
    cons: ["High cost in Amsterdam", "Housing shortage", "Dutch integration eventually required"],
    popularCourses: ["Engineering", "Agriculture", "Business", "Law", "Architecture"],
    scholarships: ["Holland Scholarship", "Orange Tulip Scholarship", "University-specific grants"],
  },
  {
    slug: "ireland",
    name: "Ireland",
    flag: "🇮🇪",
    region: "Europe",
    capital: "Dublin",
    language: "English",
    currency: "EUR (€)",
    population: "5 million",
    heroImage: "/assets/countries/ireland.jpg",
    summary: "English-speaking EU country with top tech companies and post-study work rights.",
    tuitionRange: "€9,000 – €25,000/year",
    livingCost: "€10,000 – €18,000/year",
    intakeMonths: ["September"],
    visaType: "Irish Study Visa",
    processingTime: "4–8 weeks",
    ieltsRequired: "6.0 – 6.5",
    topUniversities: ["Trinity College Dublin", "UCD", "University of Galway", "UCC", "DCU"],
    pros: ["English-speaking EU country", "Thriving tech sector (Google, Meta, Apple)", "2-year graduate stay permission", "EU open borders"],
    cons: ["High living costs in Dublin", "Housing crisis", "Limited cities"],
    popularCourses: ["Computer Science", "Business", "Finance", "Engineering", "Pharmacy"],
    scholarships: ["Government of Ireland Scholarship", "University grants", "HEA funding"],
  },
  {
    slug: "portugal",
    name: "Portugal",
    flag: "🇵🇹",
    region: "Europe",
    capital: "Lisbon",
    language: "Portuguese / English",
    currency: "EUR (€)",
    population: "10 million",
    heroImage: "/assets/countries/portugal.jpg",
    summary: "Affordable EU education, warm climate, and a welcoming culture for international students.",
    tuitionRange: "€950 – €7,000/year",
    livingCost: "€8,000 – €12,000/year",
    intakeMonths: ["September"],
    visaType: "Portuguese Student Visa",
    processingTime: "4–8 weeks",
    ieltsRequired: "5.5 – 6.5",
    topUniversities: ["University of Lisbon", "University of Porto", "Nova University Lisbon", "University of Coimbra"],
    pros: ["Very affordable tuition", "Low cost of living", "EU residency pathway", "Warm climate", "English widely spoken"],
    cons: ["Portuguese often needed for integration", "Smaller job market", "University admin can be slow"],
    popularCourses: ["Business", "Engineering", "Architecture", "Tourism", "Law"],
    scholarships: ["FCT Scholarships", "Camões Institute grants", "University merit scholarships"],
  },
  {
    slug: "sweden",
    name: "Sweden",
    flag: "🇸🇪",
    region: "Europe",
    capital: "Stockholm",
    language: "Swedish / English",
    currency: "SEK",
    population: "10 million",
    heroImage: "/assets/countries/sweden.jpg",
    summary: "High quality of life, innovative research culture, and many English-taught graduate programs.",
    tuitionRange: "SEK 80,000 – 295,000/year (non-EU)",
    livingCost: "SEK 100,000 – 130,000/year",
    intakeMonths: ["September"],
    visaType: "Swedish Residence Permit (Student)",
    processingTime: "2–4 weeks",
    ieltsRequired: "6.0 – 6.5",
    topUniversities: ["KTH Royal Institute of Technology", "Lund University", "Stockholm University", "Uppsala University"],
    pros: ["Innovation & research excellence", "English widely spoken", "High quality of life", "Work 20 hrs/week"],
    cons: ["High cost of living", "Dark winters", "Competitive market"],
    popularCourses: ["Engineering", "Computer Science", "Environmental Studies", "Business", "Design"],
    scholarships: ["Swedish Institute Scholarships", "SIDA Scholarships", "University grants"],
  },
  {
    slug: "poland",
    name: "Poland",
    flag: "🇵🇱",
    region: "Europe",
    capital: "Warsaw",
    language: "Polish / English",
    currency: "PLN",
    population: "38 million",
    heroImage: "/assets/countries/poland.jpg",
    summary: "Affordable EU education with growing English programs and a central European location.",
    tuitionRange: "€2,000 – €6,000/year",
    livingCost: "€5,000 – €9,000/year",
    intakeMonths: ["October"],
    visaType: "Polish National Visa (Type D)",
    processingTime: "2–4 weeks",
    ieltsRequired: "5.5 – 6.0",
    topUniversities: ["University of Warsaw", "Jagiellonian University", "Warsaw University of Technology", "AGH University"],
    pros: ["Very affordable compared to Western Europe", "EU membership", "Growing economy", "Safe and welcoming"],
    cons: ["Limited English programs", "Language barrier for daily life", "Colder climate"],
    popularCourses: ["Medicine", "Engineering", "IT", "Business", "Architecture"],
    scholarships: ["Polish Government Scholarship", "NAWA grants", "University scholarships"],
  },
  {
    slug: "uae",
    name: "UAE",
    flag: "🇦🇪",
    region: "Middle East",
    capital: "Abu Dhabi",
    language: "Arabic / English",
    currency: "AED",
    population: "10 million",
    heroImage: "/assets/countries/uae.jpg",
    summary: "Tax-free income, world-class infrastructure, and international branch campuses of top universities.",
    tuitionRange: "AED 30,000 – 90,000/year",
    livingCost: "AED 36,000 – 72,000/year",
    intakeMonths: ["September", "January"],
    visaType: "UAE Student Visa",
    processingTime: "2–4 weeks",
    ieltsRequired: "5.5 – 6.5",
    topUniversities: ["NYU Abu Dhabi", "Sorbonne Abu Dhabi", "American University of Sharjah", "Khalifa University"],
    pros: ["Tax-free environment", "High standard of living", "Brand-name branch campuses", "Strategic location"],
    cons: ["High living costs", "Summer heat extreme", "Limited permanent residency options"],
    popularCourses: ["Business", "Engineering", "Architecture", "Hospitality", "Finance"],
    scholarships: ["NYUAD Full Scholarship", "Khalifa University grants", "Merit scholarships"],
  },
];

export const SERVICES = [
  {
    icon: "🎓",
    title: "University Admissions",
    description: "We guide you from university selection to offer letter — application strategy, SOP review, interviews.",
    href: "/consultation",
  },
  {
    icon: "🔍",
    title: "University Search",
    description: "Search 10,000+ universities by country, ranking, tuition, program, and admission requirements.",
    href: "/universities",
  },
  {
    icon: "🏆",
    title: "Scholarship Guidance",
    description: "Find and apply for fully funded and partial scholarships matched to your profile.",
    href: "/articles/scholarship-guide",
  },
  {
    icon: "📋",
    title: "Visa Support",
    description: "Step-by-step visa preparation, document checklists, and embassy interview coaching.",
    href: "/articles/visa-guide",
  },
  {
    icon: "📝",
    title: "Document Services",
    description: "Apostille, translation, notarization, and document legalization for any country.",
    href: "/consultation",
  },
  {
    icon: "🌍",
    title: "Study Abroad Planning",
    description: "Country selection, budget planning, accommodation guidance, and pre-departure support.",
    href: "/consultation",
  },
];

export const TESTIMONIALS = [
  {
    name: "Adaeze Okonkwo",
    role: "Master's Student",
    country: "Portugal 🇵🇹",
    rating: 5,
    content: "Jandify Global helped me navigate the Portuguese university application from scratch. I'm now studying in Lisbon on a partial scholarship!",
    avatar: "AO",
  },
  {
    name: "Chukwuemeka Balogun",
    role: "DAAD Scholarship Recipient",
    country: "Germany 🇩🇪",
    rating: 5,
    content: "Got the DAAD scholarship on my first attempt thanks to Jandify's guidance. Their advisor knew exactly what German universities look for.",
    avatar: "CB",
  },
  {
    name: "Fatima Abubakar",
    role: "Work Permit Holder",
    country: "Canada 🇨🇦",
    rating: 5,
    content: "Professional service, real results. The step-by-step support made the Canadian study permit process feel manageable.",
    avatar: "FA",
  },
  {
    name: "Tobi Adewale",
    role: "Undergraduate Student",
    country: "Netherlands 🇳🇱",
    rating: 5,
    content: "Didn't think I could afford to study abroad until Jandify showed me affordable English programs in the Netherlands. Now enrolled!",
    avatar: "TA",
  },
  {
    name: "Ngozi Obi",
    role: "PhD Applicant",
    country: "France 🇫🇷",
    rating: 5,
    content: "The consultation completely changed my PhD strategy. Deep knowledge of French universities and funding options I didn't know existed.",
    avatar: "NO",
  },
  {
    name: "Emeka Okafor",
    role: "Software Engineer",
    country: "Ireland 🇮🇪",
    rating: 5,
    content: "Clear, honest guidance for my Irish work visa. The team flagged document issues before submission that could have caused rejection.",
    avatar: "EO",
  },
];

export const TEAM = [
  {
    name: "Chioma Eze",
    role: "Head of Admissions",
    bio: "10+ years guiding students to top UK and US universities. Former admissions consultant at British Council.",
    avatar: "CE",
    specialties: ["UK Universities", "US Ivy League", "Scholarships"],
  },
  {
    name: "Ibrahim Musa",
    role: "European Programs Specialist",
    bio: "MSc holder from TU Berlin. Expert in German, Dutch, and Scandinavian university applications.",
    avatar: "IM",
    specialties: ["Germany", "Netherlands", "Scandinavia"],
  },
  {
    name: "Aisha Bello",
    role: "Visa & Documentation Expert",
    bio: "Former immigration consultant. Has helped 500+ students obtain study visas across 20+ countries.",
    avatar: "AB",
    specialties: ["Visa Processing", "Document Legalization", "Immigration"],
  },
  {
    name: "Tunde Adewale",
    role: "Scholarship Advisor",
    bio: "Fulbright and Commonwealth alumnus. Guides students to fully funded programs worldwide.",
    avatar: "TA",
    specialties: ["Fulbright", "Commonwealth", "DAAD", "Chevening"],
  },
];

export const STUDY_FIELDS = [
  "Business & Management",
  "Engineering & Technology",
  "Computer Science & IT",
  "Medicine & Health Sciences",
  "Law",
  "Natural Sciences",
  "Social Sciences",
  "Arts & Humanities",
  "Architecture & Design",
  "Education",
  "Agriculture",
  "Environmental Studies",
  "Finance & Economics",
  "Psychology",
  "Media & Communications",
];

export const DEGREE_LEVELS = [
  { value: "bachelor", label: "Bachelor's Degree", duration: "3–4 years" },
  { value: "master", label: "Master's Degree", duration: "1–2 years" },
  { value: "mba", label: "MBA", duration: "1–2 years" },
  { value: "phd", label: "PhD / Doctorate", duration: "3–5 years" },
  { value: "language", label: "Language Course", duration: "1–12 months" },
  { value: "foundation", label: "Foundation Year", duration: "1 year" },
];

export const FAQS = [
  {
    q: "How does Jandify Global help me get into a university?",
    a: "We guide you through every step: choosing the right university for your profile, preparing a strong application (SOP, CV, recommendations), submitting applications, and preparing for interviews. Our advisors have helped thousands of students gain admission to top institutions.",
  },
  {
    q: "How much does the service cost?",
    a: "We offer a free 30-minute initial consultation. Our paid consultation packages start from ₦25,000 for a one-hour deep-dive session. Full application support packages vary based on your target country and number of universities.",
  },
  {
    q: "Do you guarantee admission?",
    a: "We do not guarantee admission — no ethical agency can. However, our track record shows that over 85% of students who follow our guidance receive at least one offer from their target universities.",
  },
  {
    q: "Can you help with scholarship applications?",
    a: "Yes. We help you identify scholarships you qualify for, structure your application, write compelling essays, and prepare for scholarship interviews. We've helped students secure DAAD, Chevening, Commonwealth, and many other fully funded awards.",
  },
  {
    q: "How long does the university application process take?",
    a: "The timeline varies by country and program. UK applications typically take 3–6 months, European universities 2–6 months, and US/Canada 6–12 months from initial consultation to offer letter.",
  },
  {
    q: "Do I need to speak the local language to study in Germany/France/Netherlands?",
    a: "Not necessarily. Germany, France, and the Netherlands all offer hundreds of English-taught programs, especially at the Master's level. We'll match you with programs that fit your language abilities.",
  },
];
